### Get all persons
GET http://localhost:3001/api/persons/

### Delete person with id 3
DELETE http://localhost:3001/api/persons/2

### Get updated persons
GET http://localhost:3001/api/persons/

### Post new person
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Ri",
    "number": "43-56-67856432" 
}

### Modify current person
PUT http://localhost:3001/api/persons/6948d31a5ebd6fbe2a29b7eb
Content-Type: application/json

{
    "name": "Anna",
    "number": "000000"

}