### Get all persons
GET http://localhost:3001/api/persons/

### Delete person with id 3
DELETE http://localhost:3001/api/persons/2

### Get updated persons
GET http://localhost:3001/api/persons/

### Post new person
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Richard Heize",
    "number": "43-56-67856432" 
}
